const RED_BLUE_YELLOW = 151;
const GOLD_SILVER_CRYSTAL = 251;
const RUBY_SAPPHIRE_EMERALD = 202;
const FIRE_RED_LEAF_GREEN = 151;
const DIAMOND_PEARL = 150;
const PLATINUM = 210;
const HEARTGOLD_SOULSILVER = 251;
const BLACK_WHITE = 153;
const BLACK2_WHITE2 = 300;
const X_Y_CENTRAL = 153;
const X_Y_COASTAL = 153;
const X_Y_MOUNTAIN = 151;
const OMEGA_RUBY_ALPHA_SAPPHIRE = 202; // ???
const SUN_MOON_ALOLA = 302;
const SUN_MOON_MELEMELE = 120;
const SUN_MOON_AKALA = 130;
const SUN_MOON_ULAULA = 130;
const SUN_MOON_PONI = 100;
const ULTRA_SUN_ULTRA_MOON_ALOLA = 403;
const ULTRA_SUN_ULTRA_MOON_MELEMELE = 150;
const ULTRA_SUN_ULTRA_MOON_AKALA = 160;
const ULTRA_SUN_ULTRA_MOON_ULAULA = 160;
const ULTRA_SUN_ULTRA_MOON_PONI = 130;
const LETS_GO_PIKACHU_EEVEE = 151;
const SWORD_SHIELD = 400;
const ISLE_OF_ARMOR = 211;
const CROWN_TUNDRA = 210;
const LEGENDS_ARCEUS = 242;
const SCARLET_VIOLET = 400;
const THE_TEAL_MASK = 200;
const THE_INDIGO_DISK = 243;


const POKEMON_DEX_LEGEND_ZA = 232;
const POKEMON_DEX_MEGA_DIMENSION = 132;

const DEX_LENGTHS = {
	POKEMON_DEX_LEGEND_ZA,
	POKEMON_DEX_MEGA_DIMENSION,
};

export default DEX_LENGTHS;