/**
 * 04-05-2023 Verfied data is correct - Archer
 */
const mowRotom = {
  _id: 479.5,
  name: {
    english: "Rotom",
    spanish: "Rotom",
    italian: "Rotom",
    japanese: "ロトム",
    chinese: "洛托姆",
    korean: "",
    german: "Rotom",
    french: "Motisma",
  },
  pokedexNumber: {
    swsh: 372,
    scvi: 310,
  },
  type: {
    one: "Electric",
    two: "Grass",
  },
  abilities: {
    one: {
      name: "Levitate",
      id: 26,
    },
  },
  baseStats: {
    hp: 50,
    atk: 65,
    def: 107,
    spatk: 105,
    spdef: 107,
    spd: 86,
    total: 520,
  },
  info: {
    height: "0.3 m (1′00″)",
    weight: "0.3 kg (0.7 lbs)",
  },
  gender: {
    male: "",
    female: "",
    genderless: true,
  },
  evolution: null,
  generation: 4,
  evs: {
    spatk: 1,
    spd: 1,
  },
  eggGroups: ["Amorphous"],
  species: "Plasma Pokémon",
  catchRate: 45,
  baseFriendship: 50,
  baseExp: 154,
  growthRate: "Medium Fast",
  eggCycles: 20,
  nameOrigin: {
    motor: "Rotom is ‘motor’ backwards",
  },
  gameDropDown: [
    {
      game: "Sword & Shield",
      query: "sword-shield",
    },
    {
      game: "Ultra Sun & Ultra Moon",
      query: "ultra-sun-ultra-moon",
    },
    {
      game: "Sun & Moon",
      query: "sun-moon",
    },
    {
      game: "Omega Ruby & Alpha Shappire",
      query: "omega-ruby-alpha-sapphire",
    },
    {
      game: "X & Y",
      query: "x-y",
    },
    {
      game: "Black 2 & White 2",
      query: "black-2-white-2",
    },
    {
      game: "Black & White",
      query: "black-white",
    },
    {
      game: "HeartGold & SoulSilver",
      query: "heartgold-soulsilver",
    },
    {
      game: "Platinum",
      query: "platinum",
    },
    {
      game: "Diamond & Pearl",
      query: "diamond-pearl",
    },
  ],
  pokedexEntries: {
    "mow rotom": {
      sw: "This is Rotom after it’s seized control of a lawn mower that has a special motor. As it mows down grass, it scatters the clippings everywhere.",
      sh: "In this form, Rotom focuses its antics on plants. Any flowers you were growing are going to get mowed down.",
      la: "A form in which Rotom lurks within a misshapen wheelbarrow. The wheelbarrow’s mechanisms are bizarre. It’s a bothersome Pokémon, causing trouble by mowing down grass and trees.",
    }
  },
  moves: {
    "diamond-pearl": {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Charge",
          lvl: 43,
        },
        {
          name: "Discharge",
          lvl: 50,
        },
      ],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Flash",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Endure",
        "Swagger",
        "Sleep Talk",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Snatch",
        "Secret Power",
        "Shock Wave",
        "Natural Gift",
        "Dark Pulse",
        "Charge Beam",
      ],
      special: ["Leaf Storm"],
    },
    platinum: {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Charge",
          lvl: 43,
        },
        {
          name: "Discharge",
          lvl: 50,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Flash",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Endure",
        "Swagger",
        "Sleep Talk",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Snatch",
        "Secret Power",
        "Shock Wave",
        "Natural Gift",
        "Dark Pulse",
        "Charge Beam",
      ],
      tutor: [
        "Swift",
        "Snore",
        "Spite",
        "Mud-Slap",
        "Uproar",
        "Trick",
        "Signal Beam",
        "Sucker Punch",
        "Ominous Wind",
      ],
    },
    "heartgold-soulsilver": {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Charge",
          lvl: 43,
        },
        {
          name: "Discharge",
          lvl: 50,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Flash",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Endure",
        "Swagger",
        "Sleep Talk",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Snatch",
        "Secret Power",
        "Shock Wave",
        "Natural Gift",
        "Dark Pulse",
        "Charge Beam",
      ],
      tutor: [
        "Swift",
        "Snore",
        "Spite",
        "Mud-Slap",
        "Pain Split",
        "Uproar",
        "Trick",
        "Signal Beam",
        "Sucker Punch",
        "Ominous Wind",
      ],
    },
    "black-white": {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Electro Ball",
          lvl: 43,
        },
        {
          name: "Hex",
          lvl: 50,
        },
        {
          name: "Charge",
          lvl: 57,
        },
        {
          name: "Discharge",
          lvl: 64,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Flash",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Swagger",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Charge Beam",
        "Telekinesis",
        "Round",
        "Volt Switch",
      ],
    },
    "black-2-white-2": {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Electro Ball",
          lvl: 43,
        },
        {
          name: "Hex",
          lvl: 50,
        },
        {
          name: "Charge",
          lvl: 57,
        },
        {
          name: "Discharge",
          lvl: 64,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Flash",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Swagger",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Charge Beam",
        "Telekinesis",
        "Round",
        "Volt Switch",
      ],
      tutor: [
        "Snore",
        "Spite",
        "Sleep Talk",
        "Pain Split",
        "Uproar",
        "Trick",
        "Snatch",
        "Signal Beam",
        "Dark Pulse",
        "Electroweb",
      ],
    },
    "x-y": {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Charge",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Discharge",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Electro Ball",
          lvl: 43,
        },
        {
          name: "Hex",
          lvl: 50,
        },
        {
          name: "Charge",
          lvl: 57,
        },
        {
          name: "Discharge",
          lvl: 64,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Flash",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Swagger",
        "Sleep Talk",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Dark Pulse",
        "Charge Beam",
        "Round",
        "Volt Switch",
        "Confide",
      ],
    },
    "omega-ruby-alpha-sapphire": {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Charge",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Discharge",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Electro Ball",
          lvl: 43,
        },
        {
          name: "Hex",
          lvl: 50,
        },
        {
          name: "Charge",
          lvl: 57,
        },
        {
          name: "Discharge",
          lvl: 64,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Flash",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Swagger",
        "Sleep Talk",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Secret Power",
        "Dark Pulse",
        "Charge Beam",
        "Round",
        "Volt Switch",
        "Confide",
      ],
      tutor: [
        "Snore",
        "Spite",
        "Pain Split",
        "Uproar",
        "Trick",
        "Snatch",
        "Signal Beam",
        "Shock Wave",
        "Foul Play",
        "Electroweb",
      ],
    },
    "sun-moon": {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Charge",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Discharge",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Electro Ball",
          lvl: 43,
        },
        {
          name: "Hex",
          lvl: 50,
        },
        {
          name: "Charge",
          lvl: 57,
        },
        {
          name: "Discharge",
          lvl: 64,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Swagger",
        "Sleep Talk",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Dark Pulse",
        "Charge Beam",
        "Round",
        "Volt Switch",
        "Confide",
      ],
    },
    "ultra-sun-ultra-moon": {
      "level-up": [
        {
          name: "Thunder Shock",
          lvl: 1,
        },
        {
          name: "Thunder Wave",
          lvl: 1,
        },
        {
          name: "Confuse Ray",
          lvl: 1,
        },
        {
          name: "Charge",
          lvl: 1,
        },
        {
          name: "Trick",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Discharge",
          lvl: 1,
        },
        {
          name: "Uproar",
          lvl: 8,
        },
        {
          name: "Double Team",
          lvl: 15,
        },
        {
          name: "Shock Wave",
          lvl: 22,
        },
        {
          name: "Ominous Wind",
          lvl: 29,
        },
        {
          name: "Substitute",
          lvl: 36,
        },
        {
          name: "Electro Ball",
          lvl: 43,
        },
        {
          name: "Hex",
          lvl: 50,
        },
        {
          name: "Charge",
          lvl: 57,
        },
        {
          name: "Discharge",
          lvl: 64,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Toxic",
        "Double Team",
        "Light Screen",
        "Reflect",
        "Dream Eater",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Swagger",
        "Sleep Talk",
        "Return",
        "Frustration",
        "Hidden Power",
        "Rain Dance",
        "Sunny Day",
        "Psych Up",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Dark Pulse",
        "Charge Beam",
        "Round",
        "Volt Switch",
        "Confide",
      ],
      tutor: [
        "Snore",
        "Spite",
        "Pain Split",
        "Uproar",
        "Trick",
        "Snatch",
        "Signal Beam",
        "Shock Wave",
        "Defog",
        "Telekinesis",
        "Foul Play",
        "Ally Switch",
        "Electroweb",
      ],
    },
    "sword-shield": {
      "level-up": [
        {
          name: "Double Team",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Thunder Shock",
          lvl: 5,
        },
        {
          name: "Confuse Ray",
          lvl: 10,
        },
        {
          name: "Charge",
          lvl: 15,
        },
        {
          name: "Electro Ball",
          lvl: 20,
        },
        {
          name: "Thunder Wave",
          lvl: 25,
        },
        {
          name: "Shock Wave",
          lvl: 30,
        },
        {
          name: "Hex",
          lvl: 35,
        },
        {
          name: "Substitute",
          lvl: 40,
        },
        {
          name: "Trick",
          lvl: 45,
        },
        {
          name: "Discharge",
          lvl: 50,
        },
        {
          name: "Uproar",
          lvl: 55,
        },
      ],
      special: ["Leaf Storm"],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Light Screen",
        "Reflect",
        "Swift",
        "Rest",
        "Substitute",
        "Thief",
        "Snore",
        "Protect",
        "Endure",
        "Sleep Talk",
        "Rain Dance",
        "Sunny Day",
        "Shadow Ball",
        "Uproar",
        "Will-O-Wisp",
        "Facade",
        "Helping Hand",
        "Trick",
        "Hyper Voice",
        "Dark Pulse",
        "Nasty Plot",
        "Electro Ball",
        "Foul Play",
        "Round",
        "Stored Power",
        "Ally Switch",
        "Hex",
        "Volt Switch",
        "Electroweb",
        "Eerie Impulse",
        "Electric Terrain",
      ],
      tutor: ["Rising Voltage", "Poltergeist"],
    },
    "scarlet-violet": {
      "level-up": [
        {
          name: "Double Team",
          lvl: 1,
        },
        {
          name: "Astonish",
          lvl: 1,
        },
        {
          name: "Thunder Shock",
          lvl: 5,
        },
        {
          name: "Confuse Ray",
          lvl: 10,
        },
        {
          name: "Charge",
          lvl: 15,
        },
        {
          name: "Electro Ball",
          lvl: 20,
        },
        {
          name: "Thunder Wave",
          lvl: 25,
        },
        {
          name: "Shock Wave",
          lvl: 30,
        },
        {
          name: "Hex",
          lvl: 35,
        },
        {
          name: "Substitute",
          lvl: 40,
        },
        {
          name: "Trick",
          lvl: 45,
        },
        {
          name: "Discharge",
          lvl: 50,
        },
        {
          name: "Uproar",
          lvl: 55,
        },
      ],
      machine: [
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Night Shade",
        "Confuse Ray",
        "Light Screen",
        "Reflect",
        "Swift",
        "Rest",
        "Substitute",
        "Thief",
        "Protect",
        "Endure",
        "Sleep Talk",
        "Rain Dance",
        "Sunny Day",
        "Shadow Ball",
        "Will-O-Wisp",
        "Facade",
        "Helping Hand",
        "Trick",
        "Hyper Voice",
        "Dark Pulse",
        "Nasty Plot",
        "Charge Beam",
        "Electro Ball",
        "Foul Play",
        "Stored Power",
        "Hex",
        "Volt Switch",
        "Eerie Impulse",
        "Electric Terrain",
        "Tera Blast",
      ],
      special: ["Leaf Storm"],
    },
  },
};
module.exports = mowRotom;